### PR TITLE
Optionally include platform-specific end reason codes

### PR DESCRIPTION
**Pull request by benlangfeld**
Some applications require more detailed end reasons such as circuit congestion, etc. [Asterisk](http://www.voip-info.org/wiki/view/Asterisk+variable+hangupcause) and [FreeSWITCH](http://wiki.freeswitch.org/wiki/Hangup_causes) provide their own enumerations, while other platforms (eg PRISM) might expose SIP codes or something else entirely. This patch allows for passing those specific codes up to the Rayo client after categorisation as one of the more general Rayo end reasons.

@crienzo, @bklang and @loopingrage: I'd like your input on this, please.

### CODE REVIEW

**Comment by benlangfeld** [comment]
@JustinAiken also has an interest in this

**Comment by crienzo** [comment]
I don't have a problem with this.

**Comment by crienzo** [comment]
If I were to implement this, I'd pass along FreeSWITCH's internal enumeration instead of the endpoint-specific code.

**Comment by benlangfeld** [comment]
@bklang expressed concern that `code` gives the impression of normalisation, and so I will replace this with `platform_code` to avoid ambiguity.

**Pull request merged**
