### PR TITLE
Map XMPP <message> to SIP MESSAGE?

### PR DESCRIPTION
**Pull request by chewi**
I was looking for a way to handle SIP INFO through Rayo. There don't seem to be any XEPs that are a good fit but it was mentioned that the regular XMPP <message> stanza could be used for SIP MESSAGE.

Most of Rayo is based around <iq> stanzas but I don't see why this can't be an exception. [RFC 6086](http://tools.ietf.org/html/rfc6086) says that a UA **SHOULD** send a response when receiving a SIP MESSAGE but there is no guarantee that a client actually will so perhaps the fire-and-forget nature of <message> is a good fit in this regard.

We could even take this one step further and forward any response sent using [XEP-0184](http://xmpp.org/extensions/xep-0184.html), Message Delivery Receipts.

### CODE REVIEW

**Comment by benlangfeld** [comment]
Can I get a pull request against the spec stating that a Rayo MAY support [draft-ietf-stox-im-06](http://tools.ietf.org/html/draft-ietf-stox-im-06), and describing very briefly how this would work?

**Comment by chewi** [comment]
Just a note on this statement.

> If no translation is possible then the server SHOULD return the same error but with a type of 'cancel'.

That was going to be a MUST but then I remembered that my implementation doesn't do that. As I said above, FreeSWITCH issues a SWITCH_EVENT_SEND_MESSAGE, which is handled by mod_sofia for SIP calls, but I think that other endpoint modules could handle this too. The problem is that there probably isn't any easy way to determine whether the event was totally ignored.

**Comment by benlangfeld** [comment]
```
benlangfeld: So, I don't think we need the session-im-client section. That's essentially saying "You MAY implement RFC3921", which is true of any rayo server.
Chewi: I suppose so, given this is a XEP
benlangfeld: yep
```

Other than that, this is ready to go.

**Pull request merged**
